;DS1302Memory_1829_RadioControlledTimer.inc
    
;define all memory positions used in the DS1302
    
#define DS1302_CLOCK_REGISTER_COUNT 8

;indexes to CLOCK registers
#define DS1302_SECOND   0
#define DS1302_MINUTE   1
#define DS1302_HOUR     2
#define DS1302_DATE     3
#define DS1302_MONTH    4
#define DS1302_DAY      5
#define DS1302_YEAR     6
#define DS1302_WP       7
        

